### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Dhanushvarma** [ARISE-Initiative/robomimic#114]
The following error keeps occuring when running
`pip install -e .`

`  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for egl_probe
  Running setup.py clean for egl_probe
Failed to build egl_probe
ERROR: Could not build wheels for egl_probe, which is required to install pyproject.toml-based projects
`

and this error even occurs when trying to do `pip install egl_probe` . How do i fix this, also are there any independent scripts available for postprocessing the hd5 file collected in "Robosuite" and to extract image observation from it? 

Thanks

**Comment by snasiriany** [comment]
what if you tried `pip install egl-probe==1.0.2`?

**Comment by Dhanushvarma** [comment]
Still the same issue.

**Comment by theonlynick0430** [comment]
This error has occured for me as well

**Comment by CallMeFrozenBanana** [comment]
`sudo apt install build-essential` can solve my problem.
ref: https://github.com/huggingface/lerobot/issues/105#issuecomment-2096007109

**Comment by haoyizheng2000** [comment]
cmake version matters. I also met this issue. For me, `pip install cmake ` and `sudo apt install build-essential` did not work. I solved it with `pip install cmake==3.22`, as suggested [https://github.com/isaac-sim/IsaacLab/issues/1514](url).

**Comment by lorepieri8** [comment]
cmake 3.24.2 worked for me on Mac, to avoid this issue: https://stackoverflow.com/questions/74194672/cmake-problems-after-upgrading-to-macos-13-0
