### ISSUE TITLE
Latent subgoals in gl.py

### ISSUE THREAD

**Issue by Dhanushvarma** [ARISE-Initiative/robomimic#118]
I've identified a potential issue in the implementation of the get_subgoal_predictions method in gl.py, specifically regarding the call to self.nets["goal_network"].sample_prior. The method sample_prior, as defined in vae_nets.py, requires an n argument to specify the number of samples to generate from the prior. However, this argument is not provided in the current call within get_subgoal_predictions.

In get_subgoal_predictions (gl.py):

```
latent_subgoals = self.nets["goal_network"].sample_prior(
    conditions=obs_dict,
    goals=goal_dict,
)
```

Definition of sample_prior (vae_nets.py):

```
def sample_prior(self, n, conditions=None, goals=None):
    ...
    return self.nets["prior"].sample(n=n, obs_dict=conditions, goal_dict=goals
```

Please do let me know if I am missing something

**Comment by amandlek** [comment]
I believe the number of samples is inferred from the `conditions` leading batch shape if not provided explicitly.
