### ISSUE TITLE
How do I use image dataset for lift task?

### ISSUE THREAD

**Issue by kbkartik** [ARISE-Initiative/robomimic#121]
Hi,

I am kinda new to robot manipulation as a field. I want to run a standard behavior cloning policy using images (top-down view). I have the following questions:

1. What's the difference "use_object_obs" and "use_camera_obs"?
2. When I load the "ph_lift_image" dataset, "has_offscreen_renderer" is set to True and "use_images" is set to False. How does the render simulate images during evaluation while interacting with the environment?
3. What's the difference between robomimic and robosuite?
4. For machine generated tasks, what is the formulation for dense and sparse reward functions?
5. When I run `bc.py`, the batch['obs'] gives me `['object', 'robot0_eef_pos', 'robot0_eef_quat', 'robot0_gripper_qpos']`. How can I get the `top-down` images for my BC agent?

Thanks!

**Comment by amandlek** [comment]
Some of these questions are better suited for the robosuite issues page, but I'll answer the ones relevant to robomimic here.

1. use_object_obs tells the environment to include information about objects (such as object poses) in the observations
2. if use_images is set to False, image observations are not returned by default for the agent to use. However, has_offscreen_renderer still allows the environment to render camera views as images manually (e.g. using something like this [here](https://github.com/ARISE-Initiative/robomimic/blob/b5ce96234ba2bbd3a13120046c5867453a1679cf/robomimic/scripts/playback_dataset.py#L151)
3. robomimic is a collection of datasets and learning algorithms that are independent of the simulator used to collect the data, while robosuite is a specific set of simulation environments built on top of MuJoCo. robomimic is compatible with other datasets and simulators - for example, [iGibson](https://robomimic.github.io/docs/datasets/momart.html) and [Open AI Gym](https://robomimic.github.io/docs/datasets/d4rl.html).
4. More information can be found in the robosuite environments and documentation (for example, [here](https://github.com/ARISE-Initiative/robosuite/blob/b9d8d3de5e3dfd1724f4a0e6555246c460407daa/robosuite/environments/manipulation/pick_place.py#L268))
5. This is a better question for the robosuite team. I believe there should be an existing camera called "birdview" that you should be able to use - you can pass `birdview` as a camera_names argument to our observation extraction script (see [here](https://robomimic.github.io/docs/datasets/robosuite.html#extracting-observations-from-mujoco-states) for more details). Alternatively, you can use the robosuite tune camera [script](https://github.com/ARISE-Initiative/robosuite/blob/b9d8d3de5e3dfd1724f4a0e6555246c460407daa/robosuite/scripts/tune_camera.py) to make your own camera view.
