### ISSUE TITLE
Need help with understanding data

### ISSUE THREAD

**Issue by liubaoryol** [ARISE-Initiative/robomimic#133]
I am exploring the MH square low dimensional dataset.
I do not understand what does the `states` variable mean in the dataset and how it relates to `obs`?
```
>>> dataset_path = 'robomimic/datasets/square/mh/low_dim_v141.hdf5'
>>> f = h5py.File(dataset_path, "r")
>>> f['data']['demo_0'].keys()
<KeysViewHDF5 ['actions', 'dones', 'next_obs', 'obs', 'rewards', 'states']>
```

In particular I want to know how "close" two "states" are to each other. For instance, if I want to take half of a trajectory execution performed by a better operator, and finish it with a worse operator when the "states" are close to enough to each other, to see if an algorithm, such as HBC, can distinguish between these two latent states (better and worse) during trajectory execution.
Is this something that would make sense for HBC at all or HBC is inspired on purely crossing trajectories? Also, maybe mixing like that would not give a successfully completed trajectory?

Thank you! :)

**Comment by amandlek** [comment]
The `states` entry corresponds to simulator states - in this case MuJoCo states. This is a compact representation of the simulator state, necessary to reconstruct the simulator world for different use cases, such as observation extraction (see [this](https://robomimic.github.io/docs/datasets/robosuite.html#extracting-observations-from-mujoco-states)). 

I'm a little bit confused about your second question, but it sounds like you should be comparing specific observation keys (keys under `obs`) - such as the robot state, the object states, or maybe the image observations. [Here](https://robomimic.github.io/docs/tutorials/observations.html) is some more info on observations.
