### ISSUE TITLE
How to speed up extracting observation from dataset?

### ISSUE THREAD

**Issue by AaronChuh** [ARISE-Initiative/robomimic#134]
Hi, thank you for your amazing work! 

I plan to train my own model on your dataset, but my model need depth infomation as input, which is not included in low_dim dataset. So I try to generate dataset with depth info through the script  `dataset_states_to_obs.py`. However, I find it so slow that it takes about 12 hours to convert a `.hdf5` file with 1000 trajetories on my device with RTX3090 and I9-12900K.

Could you provide some methods to speed up this process? Look forward to your reply, thanks!

**Comment by amandlek** [comment]
One option is to use multiple processes to extract observations over different demonstrations in the hdf5 - e.g. you could imagine splitting the source hdf5 into 6 pieces, and running the observation extraction script with 6 processes, and then merging the outputs together.
