### ISSUE TITLE
Changing action space to fit different controllers

### ISSUE THREAD

**Issue by CoffeePot1206** [ARISE-Initiative/robomimic#137]
Hi, I'm trying to switch from Robosuite OSC_POSE controller to JOINT_POSITION and JOINT_VELOCITY. Since the actions in the dataset is based on OSC_POSE, I need to convert these actions to fit new controllers. 

Is there any way to generate new actions based on the original dataset? Thanks!

For now I've tried to use robot_joint_pos in next_obs as the JOINT_POSITION action, but huge errors accumulate in one trajectory. Any help is appreciated :)

**Comment by amandlek** [comment]
We do not have support for this at the moment, as the functionality would likely be specific to each simulator. One promising avenue could be to use something like the approach used in ManiSkill (see section 2.2 [here](https://arxiv.org/pdf/2302.04659.pdf)).
