### ISSUE TITLE
Is there anyone suffer from OpenGL.raw.EGL._errors EGL_NOT_INITIALIZED??

### ISSUE THREAD

**Issue by mhko1998** [ARISE-Initiative/robomimic#145]
For video rendering, I was stuck with this problem. Any advice?

**Comment by amandlek** [comment]
I think it's worth raising an issue on the [robosuite](https://github.com/ARISE-Initiative/robosuite) repo for this, as it's not directly related to robomimic. 

As a note, some additional things that may help:
- What system and OS you are on, and also whether you are using a GPU
- Any other ways to reproduce the problem
