### ISSUE TITLE
robomimic for Windows 

### ISSUE THREAD

**Issue by YitzhakSp** [ARISE-Initiative/robomimic#149]
Is there a chance that at some point robomimic will be available for Windows ?

**Comment by amandlek** [comment]
robomimic should be functional on Windows as long as the simulators you are using are also functional on Windows. Did you run into any specific issue when trying installation on Windows?

**Comment by mhandb** [comment]
I think it needs this issue to be fixed: 
https://github.com/StanfordVL/egl_probe/issues/3
