### ISSUE TITLE
HBC Algorithm Suggestions

### ISSUE THREAD

**Issue by Dhanushvarma** [ARISE-Initiative/robomimic#151]
When collecting demonstrations for imitation learning algorithms, is it better to prioritize short/expert trajectories or deliberately collect long/expert trajectories to gather more data points?

 Additionally, I'm seeking suggestions from the authors on which hyper parameters to adjust in the HBC algorithm to effectively capture multi-modal behavior. Any insights or guidance would be greatly appreciated. Thank you!

**Comment by amandlek** [comment]
In my experience, shorter trajectories are usually better. 

In terms of HBC, the VAE is very sensitive to the "beta" parameter (the weight for the KL loss) - tuning that carefully is likely the most important parameter.

**Comment by Dhanushvarma** [comment]
In regards to the horizon, does it have to ve tuned as per the task, or is the recommended horizon of 10 work well across multiple tasks?

**Comment by amandlek** [comment]
It should work well, but might need tuning depending on the task.
