### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by bkpcoding** [ARISE-Initiative/robomimic#153]
Hello, I am trying to download the robomimic datasets but it seems like the server is down? I have tried all the links in this website. https://robomimic.github.io/docs/datasets/robomimic_v0.1.html

**Comment by amandlek** [comment]
Can you try again? The link is fine for me - might have been a temporary issue.

**Comment by bkpcoding** [comment]
Also I had an issue with robosuite with the new mujoco, I don't know if it is helpful to mention it in the documentation or hopefully things get fixed in mujoco's next version. https://github.com/ARISE-Initiative/robosuite/issues/481
