### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by zxfever** [ARISE-Initiative/robomimic#155]
Follow the installation tutorial and test my installation,run

` python examples/train_bc_rnn.py --debug`

I got the error
```
Traceback (most recent call last):
 File "examples/train_bc_rnn.py", line 462, in <module>
    train(config, device=device)
  File "/home/lenovo/software/robomimic/robomimic/scripts/train.py", line 77, in train
    dataset_path = os.path.expandvars(os.path.expanduser(eval_dataset_cfg["path"]))
TypeError: string indices must be integers
```
it seems that string value indexing does not appear to be supported.

All installations follow the installation tutorial.

Could you give some help?

**Comment by amandlek** [comment]
I'm guessing you're not on the master branch - this script is definitely functional on master
