### ISSUE TITLE
Replay dataset

### ISSUE THREAD

**Issue by RuiyuWANG** [ARISE-Initiative/robomimic#156]
Hi, I wonder how to replay the robomimic dataset on a customized environment. Have some trouble resetting the new environment with the initial state from the dataset.

**Comment by amandlek** [comment]
In general, it will be difficult to replay a dataset on a new customized environment, since things may have changed in the environment. You could probably manually reset the robot and object states if you want, but there won't be a great way to do this kind of thing automatically.
