### ISSUE TITLE
Object Representation

### ISSUE THREAD

**Issue by sarthakdas** [ARISE-Initiative/robomimic#171]
HI, Was wondering what exactly is being represented in objects in the array for the low dim:

[0.017, -0.11, 0.86, 0.0, 0.0, 0.5, -0.866, 0.002, 0.011, 0.174, 0.86, 0.502, 0.08, 0.045] for the can task. 

What is the meaning behind these numbers?

**Comment by sarthakdas** [comment]
('Can_pos', array([ 0.0504674 , -0.32215638,  0.86      ])), 
        ('Can_quat', array([0.        , 0.        , 0.39723027, 0.91771897])), 
        ('Can_to_robot0_eef_pos', array([0.09101279, 0.21764788, 0.15588384])), 
        ('Can_to_robot0_eef_quat', array([-0.90876   ,  0.41279432, -0.05773823,  0.02055436], dtype=float32)), the values are listed in this order

**Comment by ubless607** [comment]
@sarthakdas Where did you find this information?

**Comment by sdas-neuraco** [comment]
> @sarthakdas Where did you find this information?

I'm so sorry I don't remember, I think I ended up loading data exactly from the rldf dataset and it had these keys everytime you call step. It would be great if one of the maintainers would help out
