### ISSUE TITLE
Control the robot via waypoints (x,y,z,quaternion) rather then actions

### ISSUE THREAD

**Issue by sarthakdas** [ARISE-Initiative/robomimic#175]
Is it possible to control the robot to go to certain waypoints rather conduct certain actions, or map waypoints to actions to traverse from one waypoint to the next? 

this would be similar to inverse kinematics control rather then action control. 

Also is it possible to have a description of what is meant by action, does this mean the robot will try to change its current position by -1 or +1 in the time-step? what happens if I return action with values outside of the -1 to 1 range?

**Comment by amandlek** [comment]
This seems like a simulator-specific question, and not a question for robomimic - I'd follow up with whichever simulation framework you are using.
