### ISSUE TITLE
How to customize my own task in robomimic?

### ISSUE THREAD

**Issue by YY-GX** [ARISE-Initiative/robomimic#177]
Hi, I want to modify some tasks inside the robomimic by myself (e.g., add some object and put it somewhere...), are there any examples for doing this? Thank you!

**Comment by amandlek** [comment]
robomimic provides the policy training framework and is meant to be agnostic to underlying simulation frameworks and tasks. 

For guidance on supporting a new simulation framework, see [this](https://robomimic.github.io/docs/modules/environments.html). If you're talking about adding a new task to an existing simulation framework (for example, in [robosuite](https://robosuite.ai/)), you should look into the relevant simulation framework and perhaps post an issue on their page.

Hope this is helpful!
