### ISSUE TITLE
Robosuite can run with GLEW, but Robomimic can not.

### ISSUE THREAD

**Issue by XizoB** [ARISE-Initiative/robomimic#180]
Sorry to raise some of my confusion with you. I was able to install robomimic with robosuite before and it was working, but recently I got an error reinstalling robomimic. The strange thing is that I can call GLEW with robosuite but not with robomimic !

Robosuite-v.1.2.0
Robomimic-v0.2.0

============= Initialized Observation Utils with Obs Spec =============

using obs modality: low_dim with keys: ['robot0_eef_pos', 'object', 'robot0_gripper_qpos', 'robot0_eef_quat']
using obs modality: rgb with keys: []
using obs modality: depth with keys: []
using obs modality: scan with keys: []

============= Loaded Environment Metadata =============
obs key object with shape (10,)
obs key robot0_eef_pos with shape (3,)
obs key robot0_eef_quat with shape (4,)
obs key robot0_gripper_qpos with shape (2,)
ERROR: GLEW initalization error: Missing GL version

**Comment by amandlek** [comment]
This might be a mujoco-py issue - I believe robosuite v1.2 was still using mujoco-py instead of the DeepMind mujoco pip package.
