### ISSUE TITLE
This is Amazing 

### ISSUE THREAD

**Issue by MichaelrMentele** [ARISE-Initiative/robomimic#182]
Created this for :+1: and appreciation.

This is a very cool project. I stumbled on it while looking at robosuite. 

I've been wanting to make a 3D printable robot at home and train it to do simple tasks with "show and tell" and this brings together so much of the tooling in a really clean way.

I'll keep an eye out for areas I can contribute back to the project!

**Comment by amandlek** [comment]
Thank you for your kind words!
