### ISSUE TITLE
how to configure discrete action in bc.json

### ISSUE THREAD

**Issue by gemcollector** [ARISE-Initiative/robomimic#183]
hi, great work! I wanna ask how should I modify the `bc.json` to adapt to discrete action output?

**Comment by amandlek** [comment]
we do not support discrete actions currently - that would require extra implementation (for example, a separate policy network that treats action outputs as classification, and some postprocessing logic to take existing continuous actions in demonstrations and relabel them into discrete actions)

**Comment by arhanjain** [comment]
@amandlek if i were to implement the new algo/policy to support discretized actions for already discretized data (many including myself use robomimic as training infra so we already have discrete data from other sources), would it be possible to have it merged?

**Comment by amandlek** [comment]
Yes, definitely! It would be great to have a PR for this.
