### ISSUE TITLE
An issue about dataset.

### ISSUE THREAD

**Issue by Zhangwenyao1** [ARISE-Initiative/robomimic#188]
Thanks for your great work!
Are there any segmentation masks and depth in your dataset.

**Comment by amandlek** [comment]
These aren't available by default in the released datasets, but you should be able to use our [existing pipeline](https://robomimic.github.io/docs/datasets/robosuite.html#extracting-observations-from-mujoco-states) for observation extraction to add depth observations to the data, and modify it to add segmentation masks to the data.
