### ISSUE TITLE
Supporting custom backbone networks for VisualCore

### ISSUE THREAD

**Issue by arhanjain** [ARISE-Initiative/robomimic#189]
Because of the way the VisualCore class is written, it only allows backbones to be from the supplied base nets in the default repository. Would it make sense to instead use a registry where inheriting from ConvBase would allow any custom network to be used as a backbone for VisualCore?

`backbone_kwargs = extract_class_init_kwargs_from_dict(cls=eval(backbone_class), dic=backbone_kwargs, copy=True)`

Perhaps there's a better way to approach this than I'm thinking. My current workout is to define my own Core class that allows for using this sort of registry.

**Comment by danfeiX** [comment]
Hi @arhanjain , thanks for the note. I think a register is a great idea. It should be simple to implement too in base_net.py. Would you like to create a PR for it?

**Comment by amandlek** [comment]
Addressed by #190
