### ISSUE TITLE
Is there a dataset for the `stack` task in robomimic?

### ISSUE THREAD

**Issue by Felixvillas** [ARISE-Initiative/robomimic#194]
`DATASET_REGISTRY.keys()` returns `dict_keys(['lift', 'can', 'square', 'transport', 'tool_hang', 'lift_real', 'can_real', 'tool_hang_real'])`, so does robomimic only include datasets for these 8 tasks and not include a dataset for the stack task?

**Comment by amandlek** [comment]
Yes that's accurate but we have a dataset for the stack task as part of the [MimicGen](https://robomimic.github.io/docs/datasets/mimicgen.html) data release.
