### ISSUE TITLE
Why use regular sampling instead of reparameterized sampling with gradient during action sampling?

### ISSUE THREAD

**Issue by Dear-Chen** [ARISE-Initiative/robomimic#204]
In the bc_gmm module, I noticed that during the action sampling process, the code uses the regular sample method instead of the reparameterized rsample method, which retains gradients. Could you please explain why this choice was made?

Thank you!

**Comment by amandlek** [comment]
If I understand your question, you're asking about action sampling during inference (e.g. when sampling from the policy to play an action during policy rollouts). At inference time, we generally don't need gradients, so that's why we just use the sample method
