### ISSUE TITLE
AssertionError: OSC_POSE controller is specified, but not imported or loaded

### ISSUE THREAD

**Issue by AbdElrahmanMostafaRifaat1432** [ARISE-Initiative/robomimic#206]
![image](https://github.com/user-attachments/assets/14d86f1d-6533-4459-8af8-c914f311d3ae)

**Comment by AbdElrahmanMostafaRifaat1432** [comment]
Also your Colab code provide the same error

**Comment by lonely2silence** [comment]
Yes, I also have a same problem.

**Comment by lonely2silence** [comment]
It's a little confusing when I need to choose my keyboard layout.

**Comment by amandlek** [comment]
What's your robosuite version? I'd recommend using robosuite v1.4 or lower for now, as robosuite v1.5 has not been tested thoroughly with the examples in robomimic.

**Comment by AbdElrahmanMostafaRifaat1432** [comment]
is there an intention to put diffusion policy in robomimic or how to integerate it if you could help me I will appreciate that

**Comment by amandlek** [comment]
We have not officially integrated it (requires further cleanup and testing) but there is an unofficial release on the `robocasa` branch: https://github.com/ARISE-Initiative/robomimic/tree/robocasa

**Comment by krishanrana** [comment]
> What's your robosuite version? I'd recommend using robosuite v1.4 or lower for now, as robosuite v1.5 has not been tested thoroughly with the examples in robomimic.

But not all environments are available in v1.4. Please can you fix this.
