### ISSUE TITLE
Can it be used for offline learning?

### ISSUE THREAD

**Issue by deepakraina99** [ARISE-Initiative/robomimic#26]
I have a data collected (images and poses) from real robot. Can I use the Robomimic framework for offline learning? 

Thanks.

**Comment by amandlek** [comment]
Yes, robomimic primarily support offline learning and has been used for both simulation and real-world datasets. The only "online" part of training currently is evaluation rollouts - these can easily be disabled. However, if your real robot dataset only consists of images and poses, you will need to at least have actions defined for each timestep to train your policy. The most basic algorithm (Behavioral Cloning) only uses observations and actions for training. Please see [here](https://arise-initiative.github.io/robomimic-web/docs/introduction/datasets.html#dataset-structure) for more information on the expected dataset structure.
