### ISSUE TITLE
Ubuntu version and adaption of your project to a KUKA iiwaa

### ISSUE THREAD

**Issue by Marcelbgit** [ARISE-Initiative/robomimic#3]
Hello ARISE-Initiative team,

thanks for sharing your very exciting work and code! Could you please tell me what ubuntu version you have used (18.04? just to avoid unecessary complications)? Because of rombomimic I guess its possible to adapt your code to a KUKA iiwa. What steps would be necessary here for the robot model in the simulation? Are there also other interfaces that I need to adapt for this. I would be glad about the help and answer. I would like to test and develop your code for other applications.

Best regards,
Marcel

**Comment by amandlek** [comment]
I believe we used ubuntu 16.04. We use simulation environments provided with [robosuite](https://github.com/ARISE-Initiative/robosuite), which should already have support for the KUKA arm. You could collect your own datasets with robosuite using the KUKA arm, and you should be able to use them with robomimic - see [this link](https://arise-initiative.github.io/robomimic-web/docs/introduction/datasets.html#robosuite-hdf5-datasets) for more information. Hope that helps!
