### ISSUE TITLE
Download Server not Working

### ISSUE THREAD

**Issue by zephirefaith** [ARISE-Initiative/robomimic#34]
I am not able to download the robomimic data. I tried the webpage, wget as well as the `download_datasets.py` script.

```bash
Downloading dataset:
    task: lift
    dataset type: mh
    hdf5 type: image
    download path: <path-to>/robomimic/datasets/lift/mh

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by amandlek** [comment]
Unfortunately, I believe the servers are down currently due to some problems related to overheating - they should hopefully be back up soon (re-open the issue if you continue having issues tomorrow).
