### ISSUE TITLE
Download server still not working

### ISSUE THREAD

**Issue by zephirefaith** [ARISE-Initiative/robomimic#35]
Same as #34 still

**Comment by amandlek** [comment]
Unfortunately the power outage is persisting - what specific datasets did you need? Perhaps we can find a different way to give it to you to unblock you, for now

**Comment by zephirefaith** [comment]
Appreciate that @amandlek. I have some specific needs and want to introspect the data to see if I can extract the structure we need out of it. If I can get the Proficient-Human image-based dataset for Lift and Can for both sim and real, that'd be perfect. Does this data include depth images too or only RGB?

**Comment by snasiriany** [comment]
Hi @zephirefaith we have Lift datasets in sim and real [in this temporary link](https://drive.google.com/drive/folders/1dQa2EY9wxIMFHm07wMMnmhsVR5BqQKni?usp=sharing).

Please note, after our dataset server is back up this link may expire. We hope this helps!

**Comment by amandlek** [comment]
Servers have been back up for a while, so I am closing this issue.
