### ISSUE TITLE
Running an environment from a dataset

### ISSUE THREAD

**Issue by seann999** [ARISE-Initiative/robomimic#37]
I'm having some trouble instantiating and using an environment created with `EnvUtils.create_env_from_metadata`.
What am I missing?
![Screenshot from 2022-07-05 02-22-48](https://user-images.githubusercontent.com/6847529/177198006-b343ad9b-3b37-43ee-907e-67c966ab04ac.png)

**Comment by amandlek** [comment]
You need to instantiate `ObsUtils` - for example see [this line](https://github.com/ARISE-Initiative/robomimic/blob/master/robomimic/scripts/playback_dataset.py#L210). The reason for this is that our environment wrappers like the `EnvRobosuite` class needs to know which observations are images, in case they need to run postprocessing (e.g. converting to float, channel swap, etc). Depending on your use case, this may or may not matter. In the linked example, it does not matter, so we pass a dummy spec. If it does matter, you should explicitly specify the observation keys that should be interpreted as image observations. Hope this helps!
