### ISSUE TITLE
Environment TwoArmTransport not found

### ISSUE THREAD

**Issue by RAMBOCJ1** [ARISE-Initiative/robomimic#39]
I'm sorry to bother you, but after trying to download transport(PH)low-dim I can't get the environment to load correctly and it shows unregistered environment. But I can run the Lift dataset in the tutorial is trained properly.
![twoarm](https://user-images.githubusercontent.com/105996500/182754552-4287bd32-eb23-4e70-903a-48bbf90fd2b9.png)
![enverror](https://user-images.githubusercontent.com/105996500/182754582-d6a6e4ba-9848-4827-bb90-5a6f98d54e43.png)

Looking forward to your reply, thanks for your kind help.

**Comment by amandlek** [comment]
As mentioned [here](https://robomimic.github.io/docs/datasets/robomimic_v0.1.html#downloading) please use the `offline_study` branch of robosuite -- that branch will have the TwoArmTransport task.
