### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by lorepieri8** [ARISE-Initiative/robomimic#49]
Hi there, amazing project.

I'm considering building on top of this framework, but I would like to understand what are your plans for the future. I see that many libraries are outdated (mujoco-py not active, pytorch 1.6, python 3.7).

Which one of the below would you say is more accurate?
-Project will be maintaned with basic fixes and small updates.
-Project will be updated and will keep following the state of the art. 
-The project will be not be maintained anymore. 
-Other

**Comment by amandlek** [comment]
Thanks for reaching out - the second option ("Project will be updated and will keep following the state of the art.") is most accurate. We have been working on a new version with some feature upgrades (stay tuned - this will also include support for the new python MuJoCo bindings from DeepMind), and are also happy to accept pull requests for useful features. I should also mention that the codebase is also compatible with later versions of pytorch and python.

**Comment by lorepieri8** [comment]
Great! Can you share any ETA for the new version?

**Comment by amandlek** [comment]
We don't have one that's concrete yet - a good estimate is the next month or two.

**Comment by lorepieri8** [comment]
Was the update you mentioned part of the robosuite update or there is more to come for robomimic itself?

**Comment by amandlek** [comment]
There is more to come for robomimic - we are updating our datasets to be compatible with the new robosuite update - this feature will be released in the next few weeks.
