### ISSUE TITLE
Which MG data was used for reporting results in Table 1 (dense or sparse) ?

### ISSUE THREAD

**Issue by prajjwal1** [ARISE-Initiative/robomimic#52]
There are two versions of MG data provided (sparse and dense). The description of Table 1 doesn't specify which reward distribution was used for reporting results for MG. Since most of the data (PH and MH) provided has sparse distribution, I think sparse reward distribution might have been used for MG as well but want to confirm.

**Comment by amandlek** [comment]
Thanks for pointing this out - that's true we used sparse rewards unless otherwise mentioned across our experiments (Appendix B.1 also describes this for the Machine Generated data)
