### ISSUE TITLE
How to calculate translation from end-effector positions with Robomimic datasets

### ISSUE THREAD

**Issue by dzy666fly** [ARISE-Initiative/robomimic#60]
Hi！Thank you so much for sharing the source code. I am confused of calculating translation of the action. 

For example, as shown in the code below, the last row [ 0.40681412 -0.14598518  0.21143397] minus the fourth row  [ 0.4095132  -0.13039334  0.22040763] of end-effector x-y-z positions does not match the fourth row [ 0.00740245 -0.39340851 -0.15288217] of actions considering the sign ([-, -, -] v.s. [+, -, -] ). In addition, the value of action is also not equal to the difference between two rows of end-effector positions multiplying some constant. So how should I calculate translation? 

```
dp= './datasets/can_real/ph/image.hdf5'   
f = h5py.File(dp, 'r')   
xyz = f["data/demo_1/obs/ee_pose"][10:15,:3]  
next_xyz = np.concatenate((xyz[1:,:],xyz[-1:,:]))
difference = next_xyz-xyz
actions = f["data/demo_1/actions"][10:15,:3]

'''
print(xyz)
[[ 0.42206772 -0.07756579  0.25226842]
 [ 0.41977403 -0.08709799  0.24656297]
 [ 0.41412277 -0.11014967  0.23220704]
 [ 0.4095132  -0.13039334  0.22040763]
 [ 0.40681412 -0.14598518  0.21143397]]
print(difference)
[[-0.00229368 -0.0095322  -0.00570545]
 [-0.00565126 -0.02305168 -0.01435593]
 [-0.00460957 -0.02024367 -0.01179941]
 [-0.00269908 -0.01559184 -0.00897366]
 [ 0.          0.          0.        ]]
print(actions)
[[-0.03366617 -0.44941242 -0.20676356]
 [-0.03480152 -0.48495732 -0.22616874]
 [-0.01148498 -0.42967414 -0.18070786]
 [ 0.00740245 -0.39340851 -0.15288217]
 [ 0.0180418  -0.36251448 -0.13617327]]
print(actions[0]/difference[0])
[14.6777652  47.14678873 36.23968019]
'''
```

**Comment by amandlek** [comment]
The actions are delta pose actions - the way this works is identical to robosuite. Basically, the first 3 dimensions of the action correspond to a desired delta end effector displacement from the current end effector position. If you add this displacement to the current position, you get a desired target position -- this position is given to the OSC controller, which tries to reach it for the next control timestep. It may not necessarily reach that goal location though, so the end effector pose in the next timestep will in general be different from the commanded target position. You can read more about the logic for how delta pose actions get converted to control targets [here](https://github.com/ARISE-Initiative/robosuite/blob/aeec87157dbde50bc8a746acde14a3b345a6213b/robosuite/controllers/osc.py#L202), and more about the OSC controller [here](https://robosuite.ai/docs/modules/controllers.html#Operational-Space-Control---Pose-with-Fixed-Impedance).
