### ISSUE TITLE
Mujoco_py dependency still needed?

### ISSUE THREAD

**Issue by lorepieri8** [ARISE-Initiative/robomimic#66]
The new 0.3 version still requires mujoco_py, e.g. in the installation test "python examples/train_bc_rnn.py --debug".
Is this the expected behaviour?

**Comment by amandlek** [comment]
Thanks for bringing this to our attention! I've made a PR that addresses this issue - it is pending approval and will be merged shortly. In the meantime, feel free to copy my change locally - it is an easy fix.
