### ISSUE TITLE
Segmentation fault (core dumped) when importing robomimic.envs.env_robosuite.EnvRobosuite

### ISSUE THREAD

**Issue by caio-freitas** [ARISE-Initiative/robomimic#70]
I've been following the instruction [here](https://robomimic.github.io/docs/introduction/getting_started.html) to run the bc.json with the `datasets/lift/ph/low_dim_v141.hdf5` dataset, but it's crashing 

```
Segmentation fault (core dumped)
```

After some debugging, I have narrowed down the error to the file `utils/env_utils.py`, around line 40
```python
    env_type = get_env_type(env_meta=env_meta, env_type=env_type, env=env)
    if env_type == EB.EnvType.ROBOSUITE_TYPE:
        from robomimic.envs.env_robosuite import EnvRobosuite # This line
        return EnvRobosuite
    elif env_type == EB.EnvType.GYM_TYPE:
        from robomimic.envs.env_gym import EnvGym
        return EnvGym
    elif env_type == EB.EnvType.IG_MOMART_TYPE:
        from robomimic.envs.env_ig_momart import EnvGibsonMOMART
        return EnvGibsonMOMART
    raise Exception("code should never reach this point")
```
To make it work, I imported EnvRobosuite in the global context and removed the mentioned line. This workaround allowed me to run the code, but it's a temporary and inelegant fix. Does anyone have suggestions on what could be causing the issue?

**Comment by amandlek** [comment]
Some people have reported related issues - in those cases it's usually been another module that's at fault. Another useful debugging tip is to set a breakpoint right before the `from robomimic.envs.env_robosuite import EnvRobosuite` line and import everything that file imports one by one to track down the problematic module. One other thing is to try uninstalling mujoco and then re-installing it, and see if that makes the problem go away. Your temporary workaround of the global import is fine for now, but it's not ideal in the long run, in case you'd like to run robomimic in an environment that does not have robosuite / mujoco installed.
