### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by warmmm** [ARISE-Initiative/robomimic#79]
I install robomimic today by the source, but when I try run train_bc_rnn.py , trhere is  the error :

Error compiling Cython file:
------------------------------------------------------------
...
    See c_warning_callback, which is the C wrapper to the user defined function
    '''
    global py_warning_callback
    global mju_user_warning
    py_warning_callback = warn
    mju_user_warning = c_warning_callback
                       ^
------------------------------------------------------------

How to slove ?

**Comment by amandlek** [comment]
This seems like a mujoco installation issue. We fixed an error where the code was still trying to import `mujoco_py` (see https://github.com/ARISE-Initiative/robomimic/commit/8df6e8e482458befaf1decfcd9d635d68a7afcae) - can you verify you're on the latest master commit, and that `mujoco-py` is not installed? Also, what version of the `mujoco` package are you on?

**Comment by warmmm** [comment]
> 这似乎是 mujoco 安装问题。我们修复了代码仍在尝试导入的错误`mujoco_py`（请参阅[8df6e8e](https://github.com/ARISE-Initiative/robomimic/commit/8df6e8e482458befaf1decfcd9d635d68a7afcae)） - 您能否验证您是否使用最新的主提交，并且`mujoco-py`尚未安装？另外，`mujoco`你用的是什么版本的包？

mujoco version is 2.3.7  which is needed by the robosuite v1.4.1

**Comment by amandlek** [comment]
Can you try a lower version of mujoco (maybe `mujoco==2.3.5`)? Also please verify that `mujoco-py` is not installed.

**Comment by Nimingez** [comment]
Traceback (most recent call last):
  File "/home/nmz/robot/robosuite/robosuite/renderers/context/egl_context.py", line 155, in __del__
    self.free()
  File "/home/nmz/robot/robosuite/robosuite/renderers/context/egl_context.py", line 149, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
  File "/home/nmz/anaconda3/envs/robomimic/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglMakeCurrent,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f56ee800a40>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x7f57237ea840>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x7f57237ea840>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7f57237ea7c0>,
	),
	result = 0
)

**Comment by wangyan-hlab** [comment]
> Traceback (most recent call last): File "/home/nmz/robot/robosuite/robosuite/renderers/context/egl_context.py", line 155, in **del** self.free() File "/home/nmz/robot/robosuite/robosuite/renderers/context/egl_context.py", line 149, in free EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT) File "/home/nmz/anaconda3/envs/robomimic/lib/python3.8/site-packages/OpenGL/error.py", line 230, in glCheckError raise self._errorClass( OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED, baseOperation = eglMakeCurrent, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7f56ee800a40>, <OpenGL._opaque.EGLSurface_pointer object at 0x7f57237ea840>, <OpenGL._opaque.EGLSurface_pointer object at 0x7f57237ea840>, <OpenGL._opaque.EGLContext_pointer object at 0x7f57237ea7c0>, ), result = 0 )

I met the same issue. Any solutions?

**Comment by snasiriany** [comment]
I think this is an issue we can safely ignore. it happens when trying to free up the resources but is harmless
