### ISSUE TITLE
Ordering of time dimension for observations when sequence length is greater than 1

### ISSUE THREAD

**Issue by palashag12** [ARISE-Initiative/robomimic#93]
Hi
For an algorithm I am implementing, I am using BC-RNN with a sequence length of 10 and thus the training data is indexed in a fashion where batch is the first dimension and time is the second dimension. I also for this algorithm, however, need a second network that is conditioned only on the current (or most recent observation). It is still very unclear to me whether the data structure containing the data is ordered in such a way that the first index represents the most recent time step or the last index represents the most recent time step. 
Thanks

**Comment by amandlek** [comment]
The second dimension of the batch is in time-order. For example, batch["actions"][0] will have a sequence of actions a_t, a_{t + 1}, ..., a_{t + T - 1} where T is the sequence length.
